In [1]:
import pandas as pd
import numpy as np

In [2]:
def resumen(datos):
    return print('Forma:\n', datos.shape,'\n\n',
                 'Columnas:\n', datos.columns,'\n\n',
                 'Tipos:\n', datos.dtypes,'\n\n',
                 'Datos nulos:\n', datos.isnull().sum(),'\n\n',
                 'Cabecera:\n', datos.head(10),'\n\n',
                 'Últimos datos:\n', datos.tail(10),'\n\n',
                 'Estadísticos:\n', datos.describe([0.05,0.25,0.5,0.75,0.95])
                )

In [3]:
def truncar(numero, decimales = 0):
    return np.trunc(numero*10**decimales)/(10**decimales)

In [4]:
datos_tk3 = pd.read_csv(
        'C:\\Users\\nahue\\Desktop\\Tesis_2\\Datos\\TK3.csv',
        delimiter = ',',
        decimal = '.',
        )

In [5]:
columnas = ['Momento','TSS1','TSS2','TS1','TS2','TS3','TS4','TS_QG','U','DIR',
'PP', 'TA1','HR1','TA2','HR2','TA3','HR3','TA4','HR4','QG1','QG2','WET','RG','PAR',
'TSH1','HS1','GH1','Real(KH)1','Imag(KH)1','Real_T(KH)1','Imag_T(KH)1','TSH2',
'HS2','GH2','Real(KH)2','Imag(KH)2','Real_T(KH)2','Imag_T(KH)2','TSH3','HS3',
'GH3','Real(KH)3','Imag(KH)3','Real_T(KH)3','Imag_T(KH)3','TSH4','HS4','GH4',
'Real(KH)4','Imag(KH)4','Real_T(KH)4','Imag_T(KH)4','TSH5','HS5','GH5','Real(KH)5',
'Imag(KH)5','Real_T(KH)5','Imag_T(KH)5']
cant_col = len(columnas)
datos_conv = pd.read_csv(
        'C:\\Users\\nahue\\Desktop\\Tesis_2\\Datos\\Convencional.csv',
        delimiter = ';',
        decimal = '.',
        skiprows = [1,2],
        usecols = columnas,
        dtype = 'float64',
        engine = 'python'
        )

In [6]:
resumen(datos_tk3)

Forma:
 (26477, 62)

 Columnas:
 Index(['T_begin        ', 'T_end          ', 'u[m/s]         ',
       'v[m/s]         ', 'w[m/s]         ', 'Ts[degC]       ',
       'Tp[degC]       ', 'a[g/m3]        ', 'CO2[mmol/m3]   ',
       'T_ref[degC]    ', 'a_ref[g/m3]    ', 'p_ref[hPa]     ',
       'Var[u]         ', 'Var[v]         ', 'Var[w]         ',
       'Var[Ts]        ', 'Var[Tp]        ', 'Var[a]         ',
       'Var[CO2]       ', 'Cov[u'v']      ', 'Cov[v'w']      ',
       'Cov[u'w']      ', 'Cov[u'Ts']     ', 'Cov[v'Ts']     ',
       'Cov[w'Ts']     ', 'Cov[u'Tp']     ', 'Cov[v'Tp']     ',
       'Cov[w'Tp']     ', 'Cov[u'a']      ', 'Cov[v'a']      ',
       'Cov[w'a']      ', 'Cov[u'CO2']    ', 'Cov[v'CO2']    ',
       'Cov[w'CO2']    ', '         Nvalue', 'dir[deg]       ',
       'ustar[m/s]     ', 'HTs[W/m2]      ', 'HTp[W/m2]      ',
       'LvE[W/m2]      ', 'z/L            ', 'z/L-virt       ',
       'Flag(ustar)    ', 'Flag(HTs)      ', 'Flag(HTp)      ',
       'Flag(LvE)      ', 'Flag(wCO2)     ', '          T_mid',
       'Fcstor[mmol/m2s', '  NEE[mmol/m2s]', 'Ftprnt_trgt1[%]',
       'Ftprnt_trgt2[%]', ' Ftprnt_xmax[m]', ' r_err_ustar[%]',
       '   r_err_HTs[%]', '   r_err_LvE[%]', '   r_err_co2[%]',
       ' noise_ustar[%]', '   noise_HTs[%]', '   noise_LvE[%]',
       '   noise_co2[%]', 'Unnamed: 61'],
      dtype='object')

 Tipos:
 T_begin             object
T_end               object
u[m/s]             float64
v[m/s]             float64
w[m/s]             float64
Ts[degC]           float64
Tp[degC]           float64
a[g/m3]            float64
CO2[mmol/m3]       float64
T_ref[degC]        float64
a_ref[g/m3]        float64
p_ref[hPa]         float64
Var[u]             float64
Var[v]             float64
Var[w]             float64
Var[Ts]            float64
Var[Tp]            float64
Var[a]             float64
Var[CO2]           float64
Cov[u'v']          float64
Cov[v'w']          float64
Cov[u'w']          float64
Cov[u'Ts']         float64
Cov[v'Ts']         float64
Cov[w'Ts']         float64
Cov[u'Tp']         float64
Cov[v'Tp']         float64
Cov[w'Tp']         float64
Cov[u'a']          float64
Cov[v'a']          float64
                    ...
Cov[v'CO2']        float64
Cov[w'CO2']        float64
         Nvalue      int64
dir[deg]           float64
ustar[m/s]         float64
HTs[W/m2]          float64
HTp[W/m2]          float64
LvE[W/m2]          float64
z/L                float64
z/L-virt           float64
Flag(ustar)          int64
Flag(HTs)            int64
Flag(HTp)            int64
Flag(LvE)            int64
Flag(wCO2)           int64
          T_mid     object
Fcstor[mmol/m2s    float64
  NEE[mmol/m2s]    float64
Ftprnt_trgt1[%]    float64
Ftprnt_trgt2[%]    float64
 Ftprnt_xmax[m]    float64
 r_err_ustar[%]    float64
   r_err_HTs[%]    float64
   r_err_LvE[%]    float64
   r_err_co2[%]    float64
 noise_ustar[%]    float64
   noise_HTs[%]    float64
   noise_LvE[%]    float64
   noise_co2[%]    float64
Unnamed: 61        float64
Length: 62, dtype: object

 Datos nulos:
 T_begin                0
T_end                  0
u[m/s]              6557
v[m/s]              6557
w[m/s]              6548
Ts[degC]            2794
Tp[degC]           26477
a[g/m3]             4755
CO2[mmol/m3]        3984
T_ref[degC]         2794
a_ref[g/m3]         4755
p_ref[hPa]             0
Var[u]              6562
Var[v]              6560
Var[w]              6550
Var[Ts]             2797
Var[Tp]            26477
Var[a]              4816
Var[CO2]            4071
Cov[u'v']           6557
Cov[v'w']           6557
Cov[u'w']           6557
Cov[u'Ts']          6557
Cov[v'Ts']          6557
Cov[w'Ts']          6548
Cov[u'Tp']         26477
Cov[v'Tp']         26477
Cov[w'Tp']         26477
Cov[u'a']           8289
Cov[v'a']           8289
                   ...
Cov[v'CO2']         7608
Cov[w'CO2']         7599
         Nvalue        0
dir[deg]            6562
ustar[m/s]          6562
HTs[W/m2]           6834
HTp[W/m2]          26477
LvE[W/m2]           8418
z/L                 6548
z/L-virt            6548
Flag(ustar)            0
Flag(HTs)              0
Flag(HTp)              0
Flag(LvE)              0
Flag(wCO2)             0
          T_mid        0
Fcstor[mmol/m2s     4351
  NEE[mmol/m2s]     8445
Ftprnt_trgt1[%]     8505
Ftprnt_trgt2[%]     8505
 Ftprnt_xmax[m]     8505
 r_err_ustar[%]     6562
   r_err_HTs[%]     6835
   r_err_LvE[%]     8425
   r_err_co2[%]     7887
 noise_ustar[%]     6562
   noise_HTs[%]     6834
   noise_LvE[%]     8425
   noise_co2[%]     7887
Unnamed: 61        26477
Length: 62, dtype: int64

 Cabecera:
     T_begin           T_end            u[m/s]           v[m/s]           \
0  23.02.2018 08:37  23.02.2018 08:52              NaN              NaN
1  23.02.2018 08:52  23.02.2018 09:07              NaN              NaN
2  23.02.2018 09:07  23.02.2018 09:22              NaN              NaN
3  23.02.2018 09:22  23.02.2018 09:37              NaN              NaN
4  23.02.2018 09:37  23.02.2018 09:52              NaN              NaN
5  23.02.2018 09:52  23.02.2018 10:07              NaN              NaN
6  23.02.2018 10:07  23.02.2018 10:22              NaN              NaN
7  23.02.2018 10:22  23.02.2018 10:37              NaN              NaN
8  23.02.2018 10:37  23.02.2018 10:52              NaN              NaN
9  23.02.2018 10:52  23.02.2018 11:07              NaN              NaN

   w[m/s]           Ts[degC]         Tp[degC]         a[g/m3]          \
0              NaN        18.732616              NaN        13.673501
1              NaN        18.890680              NaN        13.626312
2              NaN        19.191111              NaN        13.641722
3              NaN        19.272028              NaN        13.401077
4              NaN        19.267708              NaN        13.658812
5              NaN        19.387197              NaN        13.552436
6              NaN        19.518814              NaN        13.654343
7              NaN        19.547535              NaN        13.570138
8              NaN        19.428974              NaN        13.525778
9              NaN        19.885784              NaN        13.118351

   CO2[mmol/m3]     T_ref[degC]      ...   Ftprnt_xmax[m]   r_err_ustar[%]  \
0        16.583342        18.732616  ...              NaN              NaN
1        16.577187        18.890680  ...              NaN              NaN
2        16.549461        19.191111  ...              NaN              NaN
3        16.548632        19.272028  ...              NaN              NaN
4        16.547024        19.267708  ...              NaN              NaN
5        16.519522        19.387197  ...              NaN              NaN
6        16.519995        19.518814  ...              NaN              NaN
7        16.542505        19.547535  ...              NaN              NaN
8        16.551220        19.428974  ...              NaN              NaN
9        16.520338        19.885784  ...              NaN              NaN

      r_err_HTs[%]     r_err_LvE[%]     r_err_co2[%]   noise_ustar[%]  \
0              NaN              NaN              NaN              NaN
1              NaN              NaN              NaN              NaN
2              NaN              NaN              NaN              NaN
3              NaN              NaN              NaN              NaN
4              NaN              NaN              NaN              NaN
5              NaN              NaN              NaN              NaN
6              NaN              NaN              NaN              NaN
7              NaN              NaN              NaN              NaN
8              NaN              NaN              NaN              NaN
9              NaN              NaN              NaN              NaN

      noise_HTs[%]     noise_LvE[%]     noise_co2[%]  Unnamed: 61
0              NaN              NaN              NaN          NaN
1              NaN              NaN              NaN          NaN
2              NaN              NaN              NaN          NaN
3              NaN              NaN              NaN          NaN
4              NaN              NaN              NaN          NaN
5              NaN              NaN              NaN          NaN
6              NaN              NaN              NaN          NaN
7              NaN              NaN              NaN          NaN
8              NaN              NaN              NaN          NaN
9              NaN              NaN              NaN          NaN

[10 rows x 62 columns]

 Últimos datos:
         T_begin           T_end            u[m/s]           v[m/s]           \
26467  31.12.2018 20:30  31.12.2018 20:45              NaN              NaN
26468  31.12.2018 20:45  31.12.2018 21:00              NaN              NaN
26469  31.12.2018 21:00  31.12.2018 21:15              NaN              NaN
26470  31.12.2018 21:15  31.12.2018 21:30              NaN              NaN
26471  31.12.2018 21:30  31.12.2018 21:45              NaN              NaN
26472  31.12.2018 21:45  31.12.2018 22:00              NaN              NaN
26473  31.12.2018 22:00  31.12.2018 22:15              NaN              NaN
26474  31.12.2018 22:15  31.12.2018 22:30              NaN              NaN
26475  31.12.2018 22:30  31.12.2018 22:45              NaN              NaN
26476  31.12.2018 22:45  31.12.2018 23:00              NaN              NaN

       w[m/s]           Ts[degC]         Tp[degC]         a[g/m3]          \
26467              NaN              NaN              NaN              NaN
26468              NaN              NaN              NaN              NaN
26469              NaN              NaN              NaN              NaN
26470              NaN              NaN              NaN              NaN
26471              NaN              NaN              NaN              NaN
26472              NaN              NaN              NaN              NaN
26473              NaN              NaN              NaN              NaN
26474              NaN              NaN              NaN              NaN
26475              NaN              NaN              NaN              NaN
26476              NaN              NaN              NaN              NaN

       CO2[mmol/m3]     T_ref[degC]      ...   Ftprnt_xmax[m]  \
26467              NaN              NaN  ...              NaN
26468              NaN              NaN  ...              NaN
26469              NaN              NaN  ...              NaN
26470              NaN              NaN  ...              NaN
26471              NaN              NaN  ...              NaN
26472              NaN              NaN  ...              NaN
26473              NaN              NaN  ...              NaN
26474              NaN              NaN  ...              NaN
26475              NaN              NaN  ...              NaN
26476              NaN              NaN  ...              NaN

        r_err_ustar[%]     r_err_HTs[%]     r_err_LvE[%]     r_err_co2[%]  \
26467              NaN              NaN              NaN              NaN
26468              NaN              NaN              NaN              NaN
26469              NaN              NaN              NaN              NaN
26470              NaN              NaN              NaN              NaN
26471              NaN              NaN              NaN              NaN
26472              NaN              NaN              NaN              NaN
26473              NaN              NaN              NaN              NaN
26474              NaN              NaN              NaN              NaN
26475              NaN              NaN              NaN              NaN
26476              NaN              NaN              NaN              NaN

        noise_ustar[%]     noise_HTs[%]     noise_LvE[%]     noise_co2[%]  \
26467              NaN              NaN              NaN              NaN
26468              NaN              NaN              NaN              NaN
26469              NaN              NaN              NaN              NaN
26470              NaN              NaN              NaN              NaN
26471              NaN              NaN              NaN              NaN
26472              NaN              NaN              NaN              NaN
26473              NaN              NaN              NaN              NaN
26474              NaN              NaN              NaN              NaN
26475              NaN              NaN              NaN              NaN
26476              NaN              NaN              NaN              NaN

       Unnamed: 61
26467          NaN
26468          NaN
26469          NaN
26470          NaN
26471          NaN
26472          NaN
26473          NaN
26474          NaN
26475          NaN
26476          NaN

[10 rows x 62 columns]

 Estadísticos:
        u[m/s]           v[m/s]           w[m/s]           Ts[degC]         \
count     19920.000000     19920.000000     19929.000000     23683.000000
mean          3.249347        -0.000107        -0.000300        13.069062
std           1.816783         0.007810         0.013652         5.828734
min          -1.795825        -0.758897        -0.767715        -2.087947
5%            0.850429         0.000000         0.000000         3.831253
25%           1.747033         0.000000         0.000000         9.087923
50%           2.986790         0.000000         0.000000        12.513522
75%           4.480351         0.000000         0.000000        16.872935
95%           6.628310         0.000000         0.000000        23.508736
max          11.580680         0.000000         0.178183        43.268578

       Tp[degC]         a[g/m3]          CO2[mmol/m3]     T_ref[degC]      \
count              0.0     21722.000000     22493.000000     23683.000000
mean               NaN        11.736372        17.774064        13.069062
std                NaN         5.989324        14.041159         5.828734
min                NaN         0.000022         6.420577        -2.087947
5%                 NaN         2.811649        14.782691         3.831253
25%                NaN         8.655518        16.180935         9.087923
50%                NaN        11.267887        16.616255        12.513522
75%                NaN        14.524449        17.164360        16.872935
95%                NaN        19.848405        21.326599        23.508736
max                NaN        89.699722       855.740112        43.268578

       a_ref[g/m3]      p_ref[hPa]       ...   Ftprnt_xmax[m]  \
count     21722.000000     26477.000000  ...     17972.000000
mean         11.736372      1015.710864  ...        24.361879
std           5.989324         6.550010  ...        63.711974
min           0.000022       994.636536  ...         0.000829
5%            2.811649      1005.982288  ...        12.317956
25%           8.655518      1011.793213  ...        15.643498
50%          11.267887      1014.570801  ...        17.273077
75%          14.524449      1020.213623  ...        19.369194
95%          19.848405      1027.655786  ...        50.974283
max          89.699722      1037.350342  ...      5741.617188

        r_err_ustar[%]     r_err_HTs[%]     r_err_LvE[%]     r_err_co2[%]  \
count     19915.000000     19642.000000     18052.000000     18590.000000
mean          5.829143        14.714304        37.865424        27.583083
std           6.215337        31.521192       124.628992        82.162469
min           1.126291         2.792074         3.684651         3.740930
5%            3.357578         6.663705         8.206147         7.967293
25%           4.048446         7.892781        10.364419         9.782598
50%           4.659180         9.150703        13.995440        12.203225
75%           5.684782        11.661809        32.772280        20.308004
95%          12.654839        33.811549       121.373187        82.380938
max         339.890167      1642.349854      8350.856445      5468.913086

        noise_ustar[%]     noise_HTs[%]     noise_LvE[%]     noise_co2[%]  \
count     19915.000000     19643.000000     18052.000000     18590.000000
mean          0.277421         1.658139         2.775610         2.208643
std           0.318476        43.832479        10.416851         9.777757
min           0.009972         0.059600         0.069390         0.000000
5%            0.135667         0.281263         0.372573         0.351534
25%           0.192005         0.444824         0.714399         0.596883
50%           0.246859         0.641641         1.032635         0.855001
75%           0.310624         0.979311         2.083223         1.462251
95%           0.444609         3.207975         9.313050         7.681513
max          22.608850      6033.718262       750.084351      1023.313294

       Unnamed: 61
count          0.0
mean           NaN
std            NaN
min            NaN
5%             NaN
25%            NaN
50%            NaN
75%            NaN
95%            NaN
max            NaN

[10 rows x 59 columns]

In [7]:
resumen(datos_conv)

Forma:
 (28058, 59)

 Columnas:
 Index(['Momento', 'TSS1', 'TSS2', 'TS1', 'TS2', 'TS3', 'TS4', 'TS_QG', 'U',
       'DIR', 'PP', 'TA1', 'HR1', 'TA2', 'HR2', 'TA3', 'HR3', 'TA4', 'HR4',
       'QG1', 'QG2', 'WET', 'RG', 'PAR', 'TSH1', 'HS1', 'GH1', 'Real(KH)1',
       'Imag(KH)1', 'Real_T(KH)1', 'Imag_T(KH)1', 'TSH2', 'HS2', 'GH2',
       'Real(KH)2', 'Imag(KH)2', 'Real_T(KH)2', 'Imag_T(KH)2', 'TSH3', 'HS3',
       'GH3', 'Real(KH)3', 'Imag(KH)3', 'Real_T(KH)3', 'Imag_T(KH)3', 'TSH4',
       'HS4', 'GH4', 'Real(KH)4', 'Imag(KH)4', 'Real_T(KH)4', 'Imag_T(KH)4',
       'TSH5', 'HS5', 'GH5', 'Real(KH)5', 'Imag(KH)5', 'Real_T(KH)5',
       'Imag_T(KH)5'],
      dtype='object')

 Tipos:
 Momento        float64
TSS1           float64
TSS2           float64
TS1            float64
TS2            float64
TS3            float64
TS4            float64
TS_QG          float64
U              float64
DIR            float64
PP             float64
TA1            float64
HR1            float64
TA2            float64
HR2            float64
TA3            float64
HR3            float64
TA4            float64
HR4            float64
QG1            float64
QG2            float64
WET            float64
RG             float64
PAR            float64
TSH1           float64
HS1            float64
GH1            float64
Real(KH)1      float64
Imag(KH)1      float64
Real_T(KH)1    float64
Imag_T(KH)1    float64
TSH2           float64
HS2            float64
GH2            float64
Real(KH)2      float64
Imag(KH)2      float64
Real_T(KH)2    float64
Imag_T(KH)2    float64
TSH3           float64
HS3            float64
GH3            float64
Real(KH)3      float64
Imag(KH)3      float64
Real_T(KH)3    float64
Imag_T(KH)3    float64
TSH4           float64
HS4            float64
GH4            float64
Real(KH)4      float64
Imag(KH)4      float64
Real_T(KH)4    float64
Imag_T(KH)4    float64
TSH5           float64
HS5            float64
GH5            float64
Real(KH)5      float64
Imag(KH)5      float64
Real_T(KH)5    float64
Imag_T(KH)5    float64
dtype: object

 Datos nulos:
 Momento           0
TSS1           1974
TSS2           1974
TS1            1974
TS2            1974
TS3            1974
TS4            1974
TS_QG          1974
U              1974
DIR            1974
PP             1974
TA1            1974
HR1            1974
TA2            1974
HR2            1974
TA3            1974
HR3            1975
TA4            1974
HR4            1974
QG1            1974
QG2            1974
WET            1974
RG             1974
PAR            2067
TSH1           1974
HS1            1974
GH1            1974
Real(KH)1      1974
Imag(KH)1      1974
Real_T(KH)1    1974
Imag_T(KH)1    1974
TSH2           1974
HS2            1974
GH2            1974
Real(KH)2      1974
Imag(KH)2      1974
Real_T(KH)2    1974
Imag_T(KH)2    1974
TSH3           9965
HS3            9965
GH3            9965
Real(KH)3      9965
Imag(KH)3      9965
Real_T(KH)3    9965
Imag_T(KH)3    9965
TSH4           1976
HS4            1976
GH4            1976
Real(KH)4      1976
Imag(KH)4      1976
Real_T(KH)4    1976
Imag_T(KH)4    1976
TSH5           1974
HS5            1974
GH5            1974
Real(KH)5      1974
Imag(KH)5      1974
Real_T(KH)5    1974
Imag_T(KH)5    1974
dtype: int64

 Cabecera:
     Momento   TSS1   TSS2    TS1    TS2    TS3    TS4  TS_QG      U    DIR  \
0  54.36458  18.15  17.97  17.89  19.35  19.21  18.66  18.47  4.701  165.8
1  54.37500  18.16  18.12  18.10  19.35  19.21  18.67  18.46  5.088  166.4
2  54.38542  18.18  18.26  18.41  19.32  19.20  18.67  18.46  5.180  166.0
3  54.39583  18.25  18.35  18.80  19.30  19.19  18.67  18.46  5.217  170.4
4  54.40625  18.35  18.53  19.07  19.26  19.16  18.65  18.47  5.059  156.8
5  54.41667    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6  54.42708  19.00  19.02  19.98  19.26  19.16  18.64  18.63  4.685  154.7
7  54.43750  19.26  19.16  20.67  19.28  19.17  18.65  18.72  4.681  157.2
8  54.44792  19.44  19.36  21.23  19.28  19.17  18.63  18.78  5.068  165.6
9  54.45833  19.69  19.51  22.01  19.28  19.16  18.63  18.89  5.128  166.3

   ...  Imag(KH)4  Real_T(KH)4  Imag_T(KH)4  TSH5    HS5    GH5  Real(KH)5  \
0  ...       82.9        19.30         89.6  19.1  1.002  0.529      117.6
1  ...       83.6        18.01         90.3  19.1  1.006  0.528      118.4
2  ...       82.4        20.63         89.1  19.1  0.974  0.535      112.0
3  ...       83.0        19.44         89.7  19.1  1.014  0.526      120.0
4  ...       82.3        20.84         89.0  19.1  1.018  0.525      120.8
5  ...        NaN          NaN          NaN   NaN    NaN    NaN        NaN
6  ...       81.1        23.51         87.8  19.1  0.982  0.534      113.6
7  ...       80.9        24.08         87.5  19.1  1.022  0.524      121.6
8  ...       81.3        23.33         87.9  19.1  1.015  0.526      120.3
9  ...       81.1        23.91         87.7  19.1  1.023  0.524      122.0

   Imag(KH)5  Real_T(KH)5  Imag_T(KH)5
0      175.3        118.8        190.3
1      175.0        119.6        189.9
2      177.5        113.1        192.6
3      174.4        121.2        189.3
4      174.1        122.0        188.9
5        NaN          NaN          NaN
6      176.6        114.6        192.0
7      173.8        122.8        188.6
8      174.4        121.5        189.1
9      173.8        123.2        188.4

[10 rows x 59 columns]

 Últimos datos:
          Momento   TSS1   TSS2    TS1    TS2    TS3    TS4  TS_QG      U  \
28048  346.53125  19.75  19.96  26.53  17.41  16.38  15.46  19.73  5.173
28049  346.54167  19.93  20.16  26.51  17.45  16.38  15.46  19.92  5.257
28050  346.55208  20.07  20.30  26.49  17.49  16.37  15.46  20.07  4.523
28051  346.56250  20.19  20.40  26.33  17.53  16.36  15.45  20.21  4.205
28052  346.57292  20.29  20.52  25.98  17.58  16.35  15.45  20.34  3.721
28053  346.58333  20.33  20.55  25.76  17.65  16.35  15.45  20.44  3.992
28054  346.59375  20.36  20.50  25.64  17.70  16.33  15.44  20.51  3.820
28055  346.60417  20.38  20.41  25.67  17.78  16.34  15.45  20.56  4.025
28056  346.61458  20.35  20.32  25.49  17.85  16.32  15.44  20.57  3.758
28057  346.62500  20.32  20.26  25.29  17.92  16.33  15.45  20.58  4.239

         DIR  ...  Imag(KH)4  Real_T(KH)4  Imag_T(KH)4  TSH5    HS5    GH5  \
28048  161.3  ...      108.0        33.77        120.2  17.0  0.989  0.529
28049  168.2  ...      107.5        34.47        119.7  17.0  0.997  0.527
28050  148.4  ...      107.7        35.70        119.9  17.0  1.008  0.529
28051  154.1  ...      108.5        31.27        120.8  17.0  0.990  0.529
28052  136.1  ...      108.2        32.88        120.4  17.0  0.995  0.528
28053  127.4  ...      108.0        34.72        120.2  17.0  1.001  0.528
28054  118.1  ...      107.8        34.32        120.0  17.0  0.993  0.528
28055  112.8  ...      107.6        34.47        119.7  17.0  0.989  0.529
28056  102.6  ...      108.0        34.44        120.2  17.0  0.994  0.530
28057   91.5  ...      108.6        31.95        120.8  17.0  0.993  0.528

       Real(KH)5  Imag(KH)5  Real_T(KH)5  Imag_T(KH)5
28048      114.9      169.4        115.4        190.3
28049      116.3      168.9        116.9        189.7
28050      119.1      169.3        119.7        190.1
28051      115.0      169.4        115.6        190.3
28052      116.0      169.0        116.5        189.8
28053      117.4      169.1        118.0        190.0
28054      115.5      169.1        116.1        190.0
28055      114.8      169.5        115.4        190.4
28056      116.1      169.7        116.7        190.6
28057      115.7      169.1        116.3        189.9

[10 rows x 59 columns]

 Estadísticos:
             Momento          TSS1          TSS2           TS1           TS2  \
count  28058.000000  26084.000000  26084.000000  26084.000000  26084.000000
mean     200.494792     12.809855     12.667990     13.112377     13.341943
std       84.372826      4.319567      4.420646      5.202829      3.832009
min       54.364580      2.050000      1.690000      0.870000      5.590000
5%        68.977607      6.190000      5.911500      5.310000      7.710000
25%      127.429685      9.140000      8.980000      9.030000      9.580000
50%      200.494790     12.940000     12.660000     12.960000     13.860000
75%      273.559895     16.300000     16.150000     16.730000     16.700000
95%      332.011981     19.460000     19.660000     21.950000     18.868500
max      346.625000     26.530000     27.640000     32.810000     21.470000

                TS3           TS4         TS_QG             U           DIR  \
count  26084.000000  26084.000000  26084.000000  26084.000000  26084.000000
mean      13.188933     13.444002     13.226538      3.107835    166.188936
std        3.369678      2.879292      4.174190      2.394442    123.944718
min        7.560000      9.410000      3.870000      0.000000      0.000000
5%         8.600000      9.850000      6.860000      0.000000      0.000000
25%        9.800000     10.430000      9.380000      1.303000     41.275000
50%       13.260000     13.000000     13.590000      2.767000    169.900000
75%       16.180000     16.370000     16.680000      4.757250    291.200000
95%       18.670000     18.280000     19.448500      7.477700    344.700000
max       20.010000     18.740000     24.430000     18.640000    360.000000

       ...     Imag(KH)4   Real_T(KH)4   Imag_T(KH)4          TSH5  \
count  ...  26082.000000  26082.000000  26082.000000  26084.000000
mean   ...     77.870939     29.260282     93.103036     13.738660
std    ...     18.290823      4.209909     21.960308      3.268572
min    ...     35.970000     10.990000     39.900000      8.800000
5%     ...     47.500500     22.150000     53.631000      9.300000
25%    ...     66.130000     27.130000     79.650000     10.400000
50%    ...     77.430000     29.400000     98.400000     13.800000
75%    ...     93.000000     31.810000    111.200000     16.780000
95%    ...    105.800000     36.240000    122.000000     19.100000
max    ...    113.300000     37.410000    126.500000     20.100000

                HS5           GH5     Real(KH)5     Imag(KH)5   Real_T(KH)5  \
count  26084.000000  26084.000000  26084.000000  26084.000000  26084.000000
mean       0.952590      0.524520    108.316333    159.084745    108.102490
std        0.060748      0.022099     11.672775      7.097509     12.037618
min        0.791000      0.471000     79.340000    144.900000     78.500000
5%         0.843000      0.477000     87.900000    148.500000     88.100000
25%        0.926000      0.506000    103.100000    153.200000    102.800000
50%        0.953000      0.535000    108.100000    158.700000    107.900000
75%        0.976000      0.542000    112.500000    164.700000    111.800000
95%        1.077000      0.547000    132.800000    170.000000    134.100000
max        1.141000      0.555000    146.700000    177.700000    147.900000

        Imag_T(KH)5
count  26084.000000
mean     188.673815
std        7.948806
min      169.300000
5%       171.700000
25%      182.000000
50%      192.600000
75%      194.800000
95%      196.900000
max      199.600000

[10 rows x 59 columns]

In [8]:
datos_conv['Dia'] = datos_conv['Momento'].apply(np.floor).astype(int)
datos_conv['Hora'] = (datos_conv['Momento']-datos_conv['Dia']) * 24
datos_conv['Hora'] = datos_conv['Hora'].round(2)

In [9]:
datos_conv['Dia'].nunique()

293

In [10]:
datos_conv['Hora'].nunique()

96

In [11]:
longitud_hora = list(range(len(datos_tk3['T_begin        '])))
for i in longitud_hora:
    horario = int(datos_tk3['T_begin        '][i][11:13]
                + datos_tk3['T_begin        '][i][14:16]
               )
    if (horario/5) != int(horario/5):
        horario = horario + 8
    horario = horario/100
    if round(horario, 1) == 23.6:
        horario = 0
    minutos = (horario - np.floor(horario)) * 100/60
    longitud_hora[i] = truncar(np.floor(horario) + minutos,
                               1)
    decimas = round(longitud_hora[i] - np.floor(longitud_hora[i]),
                    1)
    if decimas == 0.2 or decimas == 0.7:
        longitud_hora[i] = longitud_hora[i] + 0.05
    if decimas == 0.3 or decimas == 0.8:
        longitud_hora[i] = longitud_hora[i] - 0.05
    if decimas == 0.9 or decimas == 0.4:
        longitud_hora[i] = longitud_hora[i] + 0.1
datos_tk3['Hora'] = longitud_hora

In [12]:
datos_tk3['Hora'].sample(5)

23498    22.25
23132     2.75
125      16.00
6586     14.25
1474     17.25
Name: Hora, dtype: float64

In [13]:
inicio_meses_julianos = {'01':0, '02':31, '03':59, '04':90,
                         '05':120, '06':151, '07':181, '08':212,
                         '09':243, '10':273, '11':304, '12':334}
longitud_fecha = list(range(len(datos_tk3['T_begin        '])))
for i in longitud_fecha:
    dia_gregoriano = datos_tk3['T_begin        '][i][0:2]
    mes_gregoriano = datos_tk3['T_begin        '][i][3:5]
    longitud_fecha[i] = (int(dia_gregoriano)
                         + inicio_meses_julianos[mes_gregoriano]
                         )
datos_tk3['Dia'] = longitud_fecha

In [14]:
datos_tk3['Dia'].nunique()

278

In [15]:
datos_juntos = pd.merge(datos_conv,
                        datos_tk3,
                        on = ['Dia', 'Hora'],
                        how = 'outer'
                       )

In [16]:
resumen(datos_juntos)

Forma:
 (29914, 123)

 Columnas:
 Index(['Momento', 'TSS1', 'TSS2', 'TS1', 'TS2', 'TS3', 'TS4', 'TS_QG', 'U',
       'DIR',
       ...
       ' Ftprnt_xmax[m]', ' r_err_ustar[%]', '   r_err_HTs[%]',
       '   r_err_LvE[%]', '   r_err_co2[%]', ' noise_ustar[%]',
       '   noise_HTs[%]', '   noise_LvE[%]', '   noise_co2[%]', 'Unnamed: 61'],
      dtype='object', length=123)

 Tipos:
 Momento            float64
TSS1               float64
TSS2               float64
TS1                float64
TS2                float64
TS3                float64
TS4                float64
TS_QG              float64
U                  float64
DIR                float64
PP                 float64
TA1                float64
HR1                float64
TA2                float64
HR2                float64
TA3                float64
HR3                float64
TA4                float64
HR4                float64
QG1                float64
QG2                float64
WET                float64
RG                 float64
PAR                float64
TSH1               float64
HS1                float64
GH1                float64
Real(KH)1          float64
Imag(KH)1          float64
Real_T(KH)1        float64
                    ...
Cov[v'CO2']        float64
Cov[w'CO2']        float64
         Nvalue    float64
dir[deg]           float64
ustar[m/s]         float64
HTs[W/m2]          float64
HTp[W/m2]          float64
LvE[W/m2]          float64
z/L                float64
z/L-virt           float64
Flag(ustar)        float64
Flag(HTs)          float64
Flag(HTp)          float64
Flag(LvE)          float64
Flag(wCO2)         float64
          T_mid     object
Fcstor[mmol/m2s    float64
  NEE[mmol/m2s]    float64
Ftprnt_trgt1[%]    float64
Ftprnt_trgt2[%]    float64
 Ftprnt_xmax[m]    float64
 r_err_ustar[%]    float64
   r_err_HTs[%]    float64
   r_err_LvE[%]    float64
   r_err_co2[%]    float64
 noise_ustar[%]    float64
   noise_HTs[%]    float64
   noise_LvE[%]    float64
   noise_co2[%]    float64
Unnamed: 61        float64
Length: 123, dtype: object

 Datos nulos:
 Momento             1856
TSS1                3830
TSS2                3830
TS1                 3830
TS2                 3830
TS3                 3830
TS4                 3830
TS_QG               3830
U                   3830
DIR                 3830
PP                  3830
TA1                 3830
HR1                 3830
TA2                 3830
HR2                 3830
TA3                 3830
HR3                 3831
TA4                 3830
HR4                 3830
QG1                 3830
QG2                 3830
WET                 3830
RG                  3830
PAR                 3923
TSH1                3830
HS1                 3830
GH1                 3830
Real(KH)1           3830
Imag(KH)1           3830
Real_T(KH)1         3830
                   ...
Cov[v'CO2']        11045
Cov[w'CO2']        11036
         Nvalue     3437
dir[deg]            9999
ustar[m/s]          9999
HTs[W/m2]          10271
HTp[W/m2]          29914
LvE[W/m2]          11855
z/L                 9985
z/L-virt            9985
Flag(ustar)         3437
Flag(HTs)           3437
Flag(HTp)           3437
Flag(LvE)           3437
Flag(wCO2)          3437
          T_mid     3437
Fcstor[mmol/m2s     7788
  NEE[mmol/m2s]    11882
Ftprnt_trgt1[%]    11942
Ftprnt_trgt2[%]    11942
 Ftprnt_xmax[m]    11942
 r_err_ustar[%]     9999
   r_err_HTs[%]    10272
   r_err_LvE[%]    11862
   r_err_co2[%]    11324
 noise_ustar[%]     9999
   noise_HTs[%]    10271
   noise_LvE[%]    11862
   noise_co2[%]    11324
Unnamed: 61        29914
Length: 123, dtype: int64

 Cabecera:
     Momento   TSS1   TSS2    TS1    TS2    TS3    TS4  TS_QG      U    DIR  \
0  54.36458  18.15  17.97  17.89  19.35  19.21  18.66  18.47  4.701  165.8
1  54.37500  18.16  18.12  18.10  19.35  19.21  18.67  18.46  5.088  166.4
2  54.38542  18.18  18.26  18.41  19.32  19.20  18.67  18.46  5.180  166.0
3  54.39583  18.25  18.35  18.80  19.30  19.19  18.67  18.46  5.217  170.4
4  54.40625  18.35  18.53  19.07  19.26  19.16  18.65  18.47  5.059  156.8
5  54.41667    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6  54.42708  19.00  19.02  19.98  19.26  19.16  18.64  18.63  4.685  154.7
7  54.43750  19.26  19.16  20.67  19.28  19.17  18.65  18.72  4.681  157.2
8  54.44792  19.44  19.36  21.23  19.28  19.17  18.63  18.78  5.068  165.6
9  54.45833  19.69  19.51  22.01  19.28  19.16  18.63  18.89  5.128  166.3

   ...   Ftprnt_xmax[m]   r_err_ustar[%]     r_err_HTs[%]     r_err_LvE[%]  \
0  ...              NaN              NaN              NaN              NaN
1  ...              NaN              NaN              NaN              NaN
2  ...              NaN              NaN              NaN              NaN
3  ...              NaN              NaN              NaN              NaN
4  ...              NaN              NaN              NaN              NaN
5  ...              NaN              NaN              NaN              NaN
6  ...              NaN              NaN              NaN              NaN
7  ...              NaN              NaN              NaN              NaN
8  ...              NaN              NaN              NaN              NaN
9  ...              NaN              NaN              NaN              NaN

      r_err_co2[%]   noise_ustar[%]     noise_HTs[%]     noise_LvE[%]  \
0              NaN              NaN              NaN              NaN
1              NaN              NaN              NaN              NaN
2              NaN              NaN              NaN              NaN
3              NaN              NaN              NaN              NaN
4              NaN              NaN              NaN              NaN
5              NaN              NaN              NaN              NaN
6              NaN              NaN              NaN              NaN
7              NaN              NaN              NaN              NaN
8              NaN              NaN              NaN              NaN
9              NaN              NaN              NaN              NaN

      noise_co2[%]  Unnamed: 61
0              NaN          NaN
1              NaN          NaN
2              NaN          NaN
3              NaN          NaN
4              NaN          NaN
5              NaN          NaN
6              NaN          NaN
7              NaN          NaN
8              NaN          NaN
9              NaN          NaN

[10 rows x 123 columns]

 Últimos datos:
        Momento  TSS1  TSS2  TS1  TS2  TS3  TS4  TS_QG   U  DIR  ...  \
29904      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...
29905      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...
29906      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...
29907      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...
29908      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...
29909      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...
29910      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...
29911      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...
29912      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...
29913      NaN   NaN   NaN  NaN  NaN  NaN  NaN    NaN NaN  NaN  ...

        Ftprnt_xmax[m]   r_err_ustar[%]     r_err_HTs[%]     r_err_LvE[%]  \
29904              NaN              NaN              NaN              NaN
29905              NaN              NaN              NaN              NaN
29906              NaN              NaN              NaN              NaN
29907              NaN              NaN              NaN              NaN
29908              NaN              NaN              NaN              NaN
29909              NaN              NaN              NaN              NaN
29910              NaN              NaN              NaN              NaN
29911              NaN              NaN              NaN              NaN
29912              NaN              NaN              NaN              NaN
29913              NaN              NaN              NaN              NaN

          r_err_co2[%]   noise_ustar[%]     noise_HTs[%]     noise_LvE[%]  \
29904              NaN              NaN              NaN              NaN
29905              NaN              NaN              NaN              NaN
29906              NaN              NaN              NaN              NaN
29907              NaN              NaN              NaN              NaN
29908              NaN              NaN              NaN              NaN
29909              NaN              NaN              NaN              NaN
29910              NaN              NaN              NaN              NaN
29911              NaN              NaN              NaN              NaN
29912              NaN              NaN              NaN              NaN
29913              NaN              NaN              NaN              NaN

          noise_co2[%]  Unnamed: 61
29904              NaN          NaN
29905              NaN          NaN
29906              NaN          NaN
29907              NaN          NaN
29908              NaN          NaN
29909              NaN          NaN
29910              NaN          NaN
29911              NaN          NaN
29912              NaN          NaN
29913              NaN          NaN

[10 rows x 123 columns]

 Estadísticos:
             Momento          TSS1          TSS2           TS1           TS2  \
count  28058.000000  26084.000000  26084.000000  26084.000000  26084.000000
mean     200.494792     12.809855     12.667990     13.112377     13.341943
std       84.372826      4.319567      4.420646      5.202829      3.832009
min       54.364580      2.050000      1.690000      0.870000      5.590000
5%        68.977607      6.190000      5.911500      5.310000      7.710000
25%      127.429685      9.140000      8.980000      9.030000      9.580000
50%      200.494790     12.940000     12.660000     12.960000     13.860000
75%      273.559895     16.300000     16.150000     16.730000     16.700000
95%      332.011981     19.460000     19.660000     21.950000     18.868500
max      346.625000     26.530000     27.640000     32.810000     21.470000

                TS3           TS4         TS_QG             U           DIR  \
count  26084.000000  26084.000000  26084.000000  26084.000000  26084.000000
mean      13.188933     13.444002     13.226538      3.107835    166.188936
std        3.369678      2.879292      4.174190      2.394442    123.944718
min        7.560000      9.410000      3.870000      0.000000      0.000000
5%         8.600000      9.850000      6.860000      0.000000      0.000000
25%        9.800000     10.430000      9.380000      1.303000     41.275000
50%       13.260000     13.000000     13.590000      2.767000    169.900000
75%       16.180000     16.370000     16.680000      4.757250    291.200000
95%       18.670000     18.280000     19.448500      7.477700    344.700000
max       20.010000     18.740000     24.430000     18.640000    360.000000

       ...   Ftprnt_xmax[m]   r_err_ustar[%]     r_err_HTs[%]  \
count  ...     17972.000000     19915.000000     19642.000000
mean   ...        24.361879         5.829143        14.714304
std    ...        63.711974         6.215337        31.521192
min    ...         0.000829         1.126291         2.792074
5%     ...        12.317956         3.357578         6.663705
25%    ...        15.643498         4.048446         7.892781
50%    ...        17.273077         4.659180         9.150703
75%    ...        19.369194         5.684782        11.661809
95%    ...        50.974283        12.654839        33.811549
max    ...      5741.617188       339.890167      1642.349854

          r_err_LvE[%]     r_err_co2[%]   noise_ustar[%]     noise_HTs[%]  \
count     18052.000000     18590.000000     19915.000000     19643.000000
mean         37.865424        27.583083         0.277421         1.658139
std         124.628992        82.162469         0.318476        43.832479
min           3.684651         3.740930         0.009972         0.059600
5%            8.206147         7.967293         0.135667         0.281263
25%          10.364419         9.782598         0.192005         0.444824
50%          13.995440        12.203225         0.246859         0.641641
75%          32.772280        20.308004         0.310624         0.979311
95%         121.373187        82.380938         0.444609         3.207975
max        8350.856445      5468.913086        22.608850      6033.718262

          noise_LvE[%]     noise_co2[%]  Unnamed: 61
count     18052.000000     18590.000000          0.0
mean          2.775610         2.208643          NaN
std          10.416851         9.777757          NaN
min           0.069390         0.000000          NaN
5%            0.372573         0.351534          NaN
25%           0.714399         0.596883          NaN
50%           1.032635         0.855001          NaN
75%           2.083223         1.462251          NaN
95%           9.313050         7.681513          NaN
max         750.084351      1023.313294          NaN

[10 rows x 120 columns]

In [17]:
datos_juntos['Hora'].sample(5)

18302     0.25
23462    18.25
24773    10.00
24940     3.75
16395     3.50
Name: Hora, dtype: float64

In [18]:
datos_juntos['anio'] = datos_juntos['Hora']
datos_juntos.assign(anio = 2018)

,Momento,TSS1,TSS2,TS1,TS2,TS3,TS4,TS_QG,U,DIR,...,r_err_ustar[%],r_err_HTs[%],r_err_LvE[%],r_err_co2[%],noise_ustar[%],noise_HTs[%],noise_LvE[%],noise_co2[%],Unnamed: 61,anio
0,54.36458,18.15,17.97,17.89,19.35,19.21,18.66,18.47,4.701,165.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
1,54.37500,18.16,18.12,18.10,19.35,19.21,18.67,18.46,5.088,166.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
2,54.38542,18.18,18.26,18.41,19.32,19.20,18.67,18.46,5.180,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
3,54.39583,18.25,18.35,18.80,19.30,19.19,18.67,18.46,5.217,170.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
4,54.40625,18.35,18.53,19.07,19.26,19.16,18.65,18.47,5.059,156.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
5,54.41667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
6,54.42708,19.00,19.02,19.98,19.26,19.16,18.64,18.63,4.685,154.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
7,54.43750,19.26,19.16,20.67,19.28,19.17,18.65,18.72,4.681,157.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
8,54.44792,19.44,19.36,21.23,19.28,19.17,18.63,18.78,5.068,165.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
9,54.45833,19.69,19.51,22.01,19.28,19.16,18.63,18.89,5.128,166.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
10,54.46875,19.96,19.81,22.94,19.26,19.14,18.60,18.97,4.587,161.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
11,54.47917,20.28,20.18,23.80,19.27,19.13,18.60,19.17,4.617,178.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
12,54.48958,20.52,20.49,24.52,19.29,19.13,18.58,19.39,4.576,172.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
13,54.50000,20.79,20.79,25.27,19.31,19.13,18.59,19.65,4.813,167.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
14,54.51042,21.07,21.10,25.90,19.33,19.11,18.58,19.90,4.776,168.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
15,54.52083,21.38,21.40,26.41,19.37,19.11,18.58,20.15,4.491,165.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
16,54.53125,21.83,21.77,26.76,19.41,19.10,18.57,20.36,4.674,177.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
17,54.54167,22.26,21.99,27.27,19.44,19.09,18.55,20.57,4.786,173.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
18,54.55208,22.58,22.30,27.88,19.49,19.09,18.53,20.76,4.937,175.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
19,54.56250,22.78,22.27,28.32,19.54,19.07,18.51,20.95,4.794,169.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
20,54.57292,22.88,22.28,28.74,19.59,19.06,18.50,21.10,5.075,159.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
21,54.58333,22.92,22.31,29.13,19.65,19.05,18.48,21.23,5.172,150.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
22,54.59375,22.94,22.25,29.47,19.71,19.05,18.48,21.33,5.176,146.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
23,54.60417,22.87,21.97,29.88,19.77,19.04,18.48,21.40,5.364,152.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
24,54.61458,22.75,21.68,30.03,19.81,19.04,18.48,21.43,5.389,155.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
25,54.62500,22.63,21.45,29.90,19.86,19.04,18.49,21.40,4.974,166.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
26,54.63542,22.51,21.28,29.83,19.92,19.04,18.49,21.40,4.560,167.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
27,54.64583,22.35,21.15,29.80,19.97,19.03,18.48,21.40,4.578,166.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
28,54.65625,22.19,20.96,29.47,20.03,19.03,18.48,21.39,4.485,165.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29,54.66667,22.04,20.89,29.20,20.09,19.04,18.48,21.35,4.848,162.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29887,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29906,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018

In [19]:
iterador = list(range(len(datos_juntos['Flag(ustar)    '])))
for i in iterador:
    if datos_juntos['Flag(ustar)    '][i] > 6:
        datos_juntos['ustar[m/s]     '][i] = np.nan
    if datos_juntos['Flag(HTs)      '][i] > 6:
        datos_juntos['HTs[W/m2]      '][i] = np.nan
    if datos_juntos['Flag(LvE)      '][i] > 6:
        datos_juntos['LvE[W/m2]      '][i] = np.nan
    if datos_juntos['Flag(wCO2)     '][i] > 6:
        datos_juntos['  NEE[mmol/m2s]'][i] = np.nan

C:\Users\nahue\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\nahue\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\nahue\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\nahue\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [20]:
datos_juntos.isnull().sum()

Momento             1856
TSS1                3830
TSS2                3830
TS1                 3830
TS2                 3830
TS3                 3830
TS4                 3830
TS_QG               3830
U                   3830
DIR                 3830
PP                  3830
TA1                 3830
HR1                 3830
TA2                 3830
HR2                 3830
TA3                 3830
HR3                 3831
TA4                 3830
HR4                 3830
QG1                 3830
QG2                 3830
WET                 3830
RG                  3830
PAR                 3923
TSH1                3830
HS1                 3830
GH1                 3830
Real(KH)1           3830
Imag(KH)1           3830
Real_T(KH)1         3830
                   ...
Cov[w'CO2']        11036
         Nvalue     3437
dir[deg]            9999
ustar[m/s]         10266
HTs[W/m2]          10995
HTp[W/m2]          29914
LvE[W/m2]          13503
z/L                 9985
z/L-virt            9985
Flag(ustar)         3437
Flag(HTs)           3437
Flag(HTp)           3437
Flag(LvE)           3437
Flag(wCO2)          3437
          T_mid     3437
Fcstor[mmol/m2s     7788
  NEE[mmol/m2s]    12882
Ftprnt_trgt1[%]    11942
Ftprnt_trgt2[%]    11942
 Ftprnt_xmax[m]    11942
 r_err_ustar[%]     9999
   r_err_HTs[%]    10272
   r_err_LvE[%]    11862
   r_err_co2[%]    11324
 noise_ustar[%]     9999
   noise_HTs[%]    10271
   noise_LvE[%]    11862
   noise_co2[%]    11324
Unnamed: 61        29914
anio                   0
Length: 124, dtype: int64

In [21]:
datos_juntos.to_csv('C:\\Users\\nahue\\Desktop\\Tesis_2\\Datos\\Datos_juntos.csv',
                       sep = '\t',
                       na_rep = -9999,
                       index = False,
                       encoding = 'ascii'
                       )